# Generated by Django 4.1.3 on 2023-01-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('url', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
    ]
